services:
  app:
    build: .
    image: shopnova_frontend
    ports:
      - "5000:80"
    env_file:
      - .env
    networks:
      - shopnova_network
    restart: always

networks:
  shopnova_network:
    external: true

